from enum import Enum
class Responses(Enum):
    SUCCESS = 1
    FAIL = 2
    UNAUTHORIZED = 3 
    
    WORKOUT_LOG_NOT_FOUND = 404

    REQUIRED_FIELDS_MISSING = 430
    REQUIRED_FIELDS_EMPTY = 440
    NUMBERS_NOT_ALLOWED = 450
    LENGTH_NOT_ALLOWED = 460
    INVALID_EMAIL = 470
    INVALID_PASSWORD = 480

    EXCEPTION = 999

    NUMBER_OF_PAGES = 15